server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb;TRACE_LEVEL_SYSTEM_OUT=1
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect